<?php

function html_entities() {
  return array(
    '"' => '&quot;',
    '&' => '&amp;',
    '>' => '&gt;',
    '<' => '&lt;',
 // ' ' => '&nbsp;',
    '¡' => '&iexcl;',
    '¢' => '&cent;',
    '£' => '&pound;',
    '¤' => '&curren;',
    '¥' => '&yen;',
    '¦' => '&brvbar;',
    '§' => '&sect;',
    '¨' => '&uml;',
    '©' => '&copy;',
    'ª' => '&ordf;',
    '¬' => '&not;',
    '­' => '&shy;',
    '®' => '&reg;',
    '¯' => '&macr;',
    '°' => '&deg;',
    '±' => '&plusmn;',
    '²' => '&sup2;',
    '³' => '&sup3;',
    '´' => '&acute;',
    'µ' => '&micro;',
    '¶' => '&para;',
    '·' => '&middot;',
    '¸' => '&cedil;',
    '¹' => '&sup1;',
    'º' => '&ordm;',
    '»' => '&raquo;',
    '«' => '&laquo;',
    '¼' => '&frac14;',
    '½' => '&frac12;',
    '¾' => '&frac34;',
    '¿' => '&iquest;',
    'À' => '&Agrave;',
    'Á' => '&Aacute;',
    'Â' => '&Acirc;',
    'Ã' => '&Atilde;',
    'Ä' => '&Auml;',
    'Å' => '&Aring;',
    'Æ' => '&AElig;',
    'Ç' => '&Ccedil;',
    'È' => '&Egrave;',
    'É' => '&Eacute;',
    'Ê' => '&Ecirc;',
    'Ë' => '&Euml;',
    'Ì' => '&Igrave;',
    'Í' => '&Iacute;',
    'Î' => '&Icirc;',
    'Ï' => '&Iuml;',
    'Ð' => '&ETH;',
    'Ñ' => '&Ntilde;',
    'Ò' => '&Ograve;',
    'Ó' => '&Oacute;',
    'Ô' => '&Ocirc;',
    'Õ' => '&Otilde;',
    'Ö' => '&Ouml;',
    '×' => '&times;',
    'Ø' => '&Oslash;',
    'Ù' => '&Ugrave;',
    'Ú' => '&Uacute;',
    'Û' => '&Ucirc;',
    'Ü' => '&Uuml;',
    'Ý' => '&Yacute;',
    'Þ' => '&THORN;',
    'ß' => '&szlig;',
    'à' => '&agrave;',
    'á' => '&aacute;',
    'â' => '&acirc;',
    'ã' => '&atilde;',
    'ä' => '&auml;',
    'å' => '&aring;',
    'æ' => '&aelig;',
    'ç' => '&ccedil;',
    'è' => '&egrave;',
    'é' => '&eacute;',
    'ê' => '&ecirc;',
    'ë' => '&euml;',
    'ì' => '&igrave;',
    'í' => '&iacute;',
    'î' => '&icirc;',
    'ï' => '&iuml;',
    'ð' => '&eth;',
    'ñ' => '&ntilde;',
    'ò' => '&ograve;',
    'ó' => '&oacute;',
    'ô' => '&ocirc;',
    'õ' => '&otilde;',
    'ö' => '&ouml;',
    '÷' => '&divide;',
    'ø' => '&oslash;',
    'ù' => '&ugrave;',
    'ú' => '&uacute;',
    'û' => '&ucirc;',
    'ü' => '&uuml;',
    'ý' => '&yacute;',
    'þ' => '&thorn;',
    'ÿ' => '&yuml;',
    'ˆ' => '&circ;',
    '˜' => '&tilde;',
    '–' => '&ndash;',
    '—' => '&mdash;',
    '‘' => '&lsquo;',
    '’' => '&rsquo;',
    '‚' => '&sbquo;',
    '“' => '&ldquo;',
    '”' => '&rdquo;',
    '„' => '&bdquo;',
    '†' => '&dagger;',
    '‡' => '&Dagger;',
    '…' => '&hellip;',
    '‰' => '&permil;',
    '‹' => '&lsaquo;',
    '›' => '&rsaquo;',
    'Œ' => '&OElig;',
    'œ' => '&oelig;',
    'Š' => '&Scaron;',
    'š' => '&scaron;',
    'Ÿ' => '&Yuml;',
    'ƒ' => '&fnof;',
    '•' => '&bull;',
 // '″' => '&Prime;',
 // '′' => '&prime;',
    '‾' => '&oline;',
    '⁄' => '&frasl;',
    '™' => '&trade;',
    '€' => '&euro;',
    'Ø' => '&empty;',
 // '−' => '&minus;',
    '*' => '&lowast;',
    '~' => '&sim;',
    '˜' => '&asymp;',
    '·' => '&sdot;',
  );
}

function html_encode($str, $skip_html_tag_characters = false) {
  if(!$skip_html_tag_characters) {
    return strtr($str, html_entities());
  }

  $entities = html_entities();
  unset($entities['<'], $entities['>'], $entities['"'], $entities["/"]);

  return strtr($str, $entities);
}

# EOF